### ISSUE TITLE
About the account

### ISSUE THREAD

**Issue by limajun** [atmmodellect/Lecture2019#1]
When I want to copy the CDO file under  .../课件/Linux/Data/cdo-1.7.2.tar.gz to my local file contents,  I encounter an error:
cp: writing `./cdo-1.7.2.tar.gz': Disk quota exceeded.

I think it is because the Disk space is occupied.

**Comment by limajun** [comment]
my local file content is /public/home/diqiuxitong04/limajun/soft

**Comment by daxiawj** [comment]
把去年选课的帐号清理了，现在应该够了
